---
name: Publish

on:
  push:
    tags:
      - "0.*"

jobs:
  linux:
    runs-on: "ubuntu-latest"
    environment: pypi
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create publish script
        run: |
          cat <<EOF > publish.sh
          #!/bin/bash
          docker run --rm -v $(pwd):/io ghcr.io/pyo3/maturin \
            build --interpreter ${{ matrix.python-version }} --release --strip
          docker run --rm -v $(pwd):/io -e MATURIN_PYPI_TOKEN="\$1" \
            ghcr.io/pyo3/maturin publish --interpreter ${{ matrix.python-version }}
          EOF
          chmod +x publish.sh

      - name: Publish optrs
        run: |
          ./publish.sh "${{ secrets.OPT_RS_UPLOAD_TOKEN }}"

      - name: Publish optrs-api
        run: |
          cd api
          ../publish.sh "${{ secrets.OPT_RS_API_UPLOAD_TOKEN }}"

  mac:
    runs-on: "macos-latest"
    environment: pypi
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
        arch: [ "x86_64-apple-darwin", "aarch64-apple-darwin" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Create publish script
        run: |
          cat <<EOF > publish.sh
          #!/bin/bash
          maturin build --release --strip --target ${{ matrix.arch }}
          maturin publish
          EOF
          chmod +x publish.sh

      - name: Allow cross compiling
        if: ${{ matrix.arch == 'aarch64-apple-darwin' }}
        run: rustup target add ${{ matrix.arch }}

      - name: Publish optrs
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.OPT_RS_UPLOAD_TOKEN }}
        run: ./publish.sh

      - name: Publish optrs-api
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.OPT_RS_API_UPLOAD_TOKEN }}
        run: cd api && ../publish.sh
